### ISSUE TITLE
Relation Widget for file, search not updating results

### ISSUE THREAD

**Issue by preetamslot** [StaticJsCMS/static-cms#853]
It looks like the UI is not updating on  search.

field:
```
{
	name: 'icons',
	label: t('icon'),
	widget: 'relation',
	collection: 'config',
	required: false,
	file: 'src/content/config/icon_list.mdx',
	search_fields: ['icons.*.name'],
	display_fields: ['icons.*.name'],
	options_length: 200,
	value_field: 'icons.*.icon'
},
```

icon_list:
```
icons:
  - name: right
    icon: /src/icons/right.svg
  - name: left
    icon: /src/icons/left.svg
  - name: download
    icon: /src/icons/download.svg
    ...
 - name: zoom
    icon: /src/icons/zoom.svg

```
search for "zoom" (last icon in the list)
![image](https://github.com/StaticJsCMS/static-cms/assets/5420582/28e45257-c5ef-4166-bc6c-d8c69344b111)

Search for name that is not in the icons:
![image](https://github.com/StaticJsCMS/static-cms/assets/5420582/61dd1c58-2e8a-4c4f-82de-a9a4a574942d)

how can I fix this?

p.s this field/widget is nested

**Comment by KaneFreeman** [comment]
This is fixed in version `3.0.2`.

**Comment by preetamslot** [comment]
@KaneFreeman 
Thanks for the update, it still does not work the way it should:

https://github.com/StaticJsCMS/static-cms/assets/5420582/9273f498-d316-419a-8f1d-d9a7960a4967

As you can see on page load you can see all values, but the filter does not work and after interaction only the selected value is visible.

It is also not possible to clear a value on a relation with `multiple: false,`


```javascript
{
			name: 'icon',
			label: t('icon'),
			widget: 'relation',
			collection: 'config',
			required: false,
			file: 'src/content/config/icons.mdx',
			search_fields: ['icons.*.name'],
			display_fields: ['icons.*.name'],
			options_length: 50,
			value_field: 'icons.*.icon'
		},
		{
			name: 'hero_surface',
			label: t('hero_surface'),
			multiple: false,
			widget: 'relation',
			collection: 'config',
			file: 'src/content/config/style.mdx',
			search_fields: ['surface.*.name'],
			display_fields: ['surface.*.name'],
			value_field: 'surface.*.class',
			options_length: 50,
			required: false
		},
```
style.mdx



```markdown
---
surface:
  - name: base
    class: surface-base
  - name: primary
    class: surface-primary
  - name: secondary
    class: surface-secondary
  - name: light
    class: surface-light
  - name: dark
    class: surface-dark
  - name: accent
    class: surface-accent
  - name: warning
    class: surface-warning
  - class: surface-danger
    name: danger
  - name: info
    class: surface-info
  - name: success
    class: surface-success
  - name: light Slate
    class: bg-slate-200 text-dark dark:bg-slate-600 dark:text-white
---

```

**Comment by KaneFreeman** [comment]
Your `file` field is incorrect. It should be the name of the file as specified in your collection, not the actual path to it.

So if your config was like this:

```js
collections: [
  {
    name: 'other-collection',
    label: 'Other Collection',
    fields: [
      {
        name: 'icon',
        label: t('icon'),
        widget: 'relation',
        collection: 'config',
        required: false,
        file: 'icons',
        search_fields: ['icons.*.name'],
        display_fields: ['icons.*.name'],
        options_length: 50,
        value_field: 'icons.*.icon'
      }
    ]
  },
  {
    name: 'settings',
    label: 'Settings',
    files: [
      {
        name: 'icons',
        label: 'Icons',
        file: 'src/content/config/icons.mdx',
        fields: [...]
      }
    ]
  }
]
```

**Comment by preetamslot** [comment]
@KaneFreeman 
Thanks! that worked, so the file field is for the file name, not the file location, my bad .

Last question, how can you clear the field?
For me it is only possible when you set multiple to true.

**Comment by KaneFreeman** [comment]
Version `3.1.0` added a clear button to the relation widget.
